site_name: 王大爷的学习笔记
theme:
  name: 'material'
  language: zh
  features:
    - toc.integrate
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.prune
    - navigation.top
#    - navigation.footer

  palette:
    - primary: black

repo_url: https://github.com/shiyeah/docs
repo_name: shiyeah/docs


nav:
  - 主页: index.md
  - Linux:
    - Ubuntu Server:
      - Ubuntu20.04 安装后配置: ./1_Linux/ubuntu20.04_system_setup.md
      - Ubuntu20.04 LNMP: ./1_Linux/ubuntu20.04_lnmp_php_mysql.md
      - Ubuntu20.04 Gitlab: ./1_Linux/ubuntu20.04_gitlab.md
      - Ubuntu20.04 Gitlab Nginx: ./1_Linux/ubuntu20.04_gitlab_nginx.md
      - Ubuntu20.04 Gitlab ElasticSearch: ./1_Linux/ubuntu20.04_gitlab_elastic.md
      - Ubuntu20.04 Gitlab License: ./1_Linux/ubuntu20.04_gitlab_license.md
    - Linux踩过的坑: ./1_Linux/1_faq.md
  - MacOS:
    - 安装黑苹果:
      - 定制USB接口: ./2_MacOS/2_1_0_usb.md
      - OpenCore制作: ./2_MacOS/2_1_1_opencore_efi.md
      - 制作MacOS引导U盘: ./2_MacOS/2_1_2_macos_uboot.md
    - Typora搭配PICGO APP用七牛做图床: ./2_MacOS/MacOS_Typora_PICGO_qiniu.md
    - MacOS踩过的坑: ./2_MacOS/2_faq.md
  - Windows:
    - Windows踩过的坑: ./3_Windows/3_faq.md
  - 存储NAS:
      - Synology:
        - Synology: ./4_Storage_Nas/4_1_synology.md
        - Synology7: ./4_Storage_Nas/synology7.md
      - TrueNAS: ./4_Storage_Nas/4_2_truenas.md
      - 存储NAS踩过的坑: ./4_Storage_Nas/4_faq.md
  - 软路由:
      - Router OS: ./5_Router/5_1_ros.md
      - OpenWRT: ./5_Router/5_2_openwrt.md
      - 软路由踩过的坑: ./5_Router/5_faq.md
  - 网络及其他:
      - 交换机: ./6_Network/6_1_switch.md
      - 网络踩过的坑: ./6_Network/6_faq.md
  - 嵌入式开发:
      - STM32:
          - STM32开发环境软件安装: ./7_Embedded/7_1_0_soft.md
          - 示例1-点灯: ./7_Embedded/7_1_1_gpio_led.md
      - STM32踩过的坑: ./7_Embedded/7_faq.md
  - 编程开发:
      - Git常用命令: ./8_Dev/git_users.md
      - 编程开发踩过的坑: ./8_Dev/8_faq.md
  - WEB:
      - HEXO:
        - hexo 安装: ./9_WEB/hexo_install_users.md
        - hexo fluid主题: ./9_WEB/hexo_fluid_theme.md
        - hexo Gitrunner: ./9_WEB/hexo_gitrunner.md
      - WEB踩过的坑: ./9_WEB/9_faq.md
  - 摄影:
      - 摄影踩过的坑: ./20_Picture/20_faq.md
  - 音频:
      - 音频踩过的坑: ./21_Audio/21_faq.md
  - 视频:
      - 视频踩过的坑: ./22_Video/22_faq.md
  - 游戏:
      - 游戏:
        - CS服务器:
          - HLDS架设: ./23_Game/23_1_hlds.md
          - Ubuntu STEAM安装: ./23_Game/ubuntu20.04_steam.md
          - HLDS 插件安装: ./23_Game/steam_hlds_addons.md
          - HLDS SQL插件安装: ./23_Game/steam_hlds_amxx_admin_sql.md
      - 游戏踩过的坑: ./23_Game/23_faq.md

markdown_extensions:
  - toc:
      toc_depth: 3

extra_javascript:
  - 'javascripts/busuanzi.pure.mini.js'
  - 'javascripts/shortcuts.js'

plugins:
  - search:
      lang: zh
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      fallback_to_build_date: true


extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://doc.sinnen.top:8443
      name: Newren

copyright: Copyright &copy; 2015 - 2024 Newren