site_name: 王大爷的学习笔记
theme:
  name: 'material'
  language: zh
repo_url: https://git.sinnen.top:8443/root/wwdocs

nav:
  - 主页: index.md
  - Linux:
    - Linux介绍: ./1_Linux/1_Linux.md
    - Ubuntu:
      - Ubuntu介绍: ./1_Linux/1_1_Ubuntu.md
      - Ubuntu20.04 系统安装: ./1_Linux/ubuntu20.04_system_setup.md
    - 踩过的坑: ./1_Linux/1_faq.md
  - MacOS:
    - MacOS: ./2_MacOS/2_MacOS.md
    - 安装黑苹果:
      - 黑苹果介绍: ./2_MacOS/2_1_hackintosh.md
      - 定制USB接口: ./2_MacOS/2_1_0_usb.md
      - OpenCore制作: ./2_MacOS/2_1_1_opencore_efi.md
      - 制作MacOS引导U盘: ./2_MacOS/2_1_2_macos_uboot.md
    - 踩过的坑: ./2_MacOS/2_faq.md
  - Windows:
    - Windows介绍: ./3_Windows/3_Windows.md
    - 踩过的坑: ./3_Windows/3_faq.md
  - 存储NAS:
      - 存储系统: ./4_Storage_Nas/4_Storage_Nas.md
      - Synology: ./4_Storage_Nas/4_1_synology.md
      - TrueNAS: ./4_Storage_Nas/4_2_truenas.md
      - 踩过的坑: ./4_Storage_Nas/4_faq.md
  - 软路由:
      - 软路由介绍: ./5_Router/5_Router.md
      - Router OS: ./5_Router/5_1_ros.md
      - OpenWRT: ./5_Router/5_2_openwrt.md
      - 踩过的坑: ./5_Router/5_faq.md
  - 网络及其他:
      - 网络: ./6_Network/6_Network.md
      - 交换机: ./6_Network/6_1_switch.md
      - 踩过的坑: ./6_Network/6_faq.md
  - 嵌入式开发:
      - 嵌入式介绍: ./7_Embedded/7_Embedded.md
      - STM32:
          - STM32介绍: ./7_Embedded/7_1_stm32.md
          - STM32开发环境软件安装: ./7_Embedded/7_1_0_soft.md
          - 示例1-点灯: ./7_Embedded/7_1_1_gpio_led.md
      - 踩过的坑: ./7_Embedded/7_faq.md
  - 编程开发:
      - 编程开发: ./8_Dev/8_Dev.md
      - C语言: ./8_Dev/8_faq.md
      - 踩过的坑: ./8_Dev/8_faq.md
  - 摄影:
      - 摄影: ./20_Picture/20_Picture.md
      - 踩过的坑: ./20_Picture/20_faq.md
  - 音频:
      - 音频: ./21_Audio/21_Audio.md
      - 踩过的坑: ./21_Audio/21_faq.md
  - 视频:
      - 视频: ./22_Video/22_video.md
      - 踩过的坑: ./22_Video/22_faq.md
  - 游戏:
      - 游戏: ./23_Game/23_Game.md
      - CS服务器:
        - HLDS架设: ./23_Game/23_1_hlds.md
      - 踩过的坑: ./23_Game/23_faq.md
  - 其他:
      - 其他: ./30_Other/30_Other.md
  - 关于: about.md
  - Foo: foo.md
  - Bar: bar.md


markdown_extensions:
  - toc:
      toc_depth: 3


plugins:
  - search:
      lang: zh
